### PR TITLE
Fix PHP notices - Issue 1124

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: Islandora-CLAW/CLAW/issues/1124 and Islandora-CLAW/CLAW/issues/1125

# What does this Pull Request do?

Resolves PHP notices about missing settings for the viewer and settings form. Also fixes some minor form errors.

# What's new?

* Changes various form default setting code to see if the setting is set and using blank values if not.
* Added fit_to_aspect_ratio to openseadragon.settings (set to false, makes explicit that which was implicit)
* Removed a duplicate settings form item (controlsFadeDelay) and fixes the title for another (maxImageCacheCount)
* Does this change require documentation to be updated? No
* Does this change add any new dependencies? No
* Does this change require any other modifications to be made to the repository
 (ie. Regeneration activity, etc.)? No
* Could this change impact execution of existing code? No

# How should this be tested?

* View an item with the Open Seadragon viewer
* View the Open Seadragon settings form (http://localhost:8000/admin/config/media/openseadragon)
* Check the log (http://localhost:8000/admin/reports/dblog) and you should see a bunch of notices corresponding to the original issue.
* Apply the PR
* Since we don't have features to help us: import the new openseadragon.settings using the Config Sync tool (http://localhost:8000/admin/config/development/configuration/single/import) using the "Simple Configuration" type.
* View the item again.
* View the Open Seadragon settings form again.
* There should be no new notices in your logs.

# Interested parties
@kayakr, @Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
@seth-shaw-unlv what about all the other settings not included in the install config which instead now have these defaults in the form?

Basically everywhere you have added an `isset()` that variable should be in the `config/install/openseadragon.settings.yml` 

Or I think all of them, at least the first 7 but then I stopped checking

**Comment by whikloj** [comment]
Then the config is loaded at install time and the `isset()`s are not required.

**Comment by seth-shaw-unlv** [comment]
@whikloj The ones I added the isset for (e.g. compositeOperation) didn't have entries in openseadragon.settings. True, adding them there would be simpler, but I didn't know what a reasonable default would be, so I opted for checking instead.

Should I just change this PR to give them all blank values in the config?

**Comment by whikloj** [comment]
@seth-shaw-unlv Can we not add a default of `''` in the Yaml?

**Comment by seth-shaw-unlv** [comment]
@whikloj, probably. I'll try it once I'm done testing a different PR.

**Comment by seth-shaw-unlv** [comment]
I've added default settings to config and reverted the issets. How's it look @whikloj?

**Pull request merged**
